name: Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  wiki:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check local links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2
        with:
          args: --offline --include-fragments --no-progress './**/*.md'
          lycheeVersion: v0.24.2
          output: ${{ runner.temp }}/wiki-links.md
